package com.ib.client;

import org.junit.runner.RunWith;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectClasses;

@RunWith(value = JUnitPlatform.class)
@SelectClasses(value = { ScannerSubscription_numberOfRows_0_0_Test.class, ScannerSubscription_instrument_1_0_Test.class, ScannerSubscription_locationCode_2_0_Test.class, ScannerSubscription_scanCode_3_1_Test.class, ScannerSubscription_abovePrice_4_1_Test.class, ScannerSubscription_belowPrice_5_0_Test.class, ScannerSubscription_aboveVolume_6_0_Test.class, ScannerSubscription_averageOptionVolumeAbove_7_0_Test.class, ScannerSubscription_marketCapAbove_8_1_Test.class, ScannerSubscription_marketCapBelow_9_0_Test.class, ScannerSubscription_moodyRatingAbove_10_1_Test.class, ScannerSubscription_moodyRatingBelow_11_0_Test.class, ScannerSubscription_spRatingAbove_12_0_Test.class, ScannerSubscription_spRatingBelow_13_0_Test.class, ScannerSubscription_maturityDateAbove_14_0_Test.class, ScannerSubscription_maturityDateBelow_15_0_Test.class, ScannerSubscription_couponRateAbove_16_0_Test.class, ScannerSubscription_couponRateBelow_17_0_Test.class, ScannerSubscription_excludeConvertible_18_1_Test.class, ScannerSubscription_scannerSettingPairs_19_0_Test.class, ScannerSubscription_stockTypeFilter_20_0_Test.class, ScannerSubscription_numberOfRows_21_0_Test.class, ScannerSubscription_abovePrice_25_0_Test.class, ScannerSubscription_belowPrice_26_1_Test.class, ScannerSubscription_aboveVolume_27_0_Test.class, ScannerSubscription_averageOptionVolumeAbove_28_0_Test.class, ScannerSubscription_marketCapAbove_29_0_Test.class, ScannerSubscription_couponRateAbove_37_2_Test.class, ScannerSubscription_couponRateBelow_38_0_Test.class })
public class ScannerSubscription_Suite {
}
