package com.ib.client;

import org.junit.runner.RunWith;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectClasses;

@RunWith(value = JUnitPlatform.class)
@SelectClasses(value = { EWrapperMsgGenerator_tickPrice_0_3_Test.class, EWrapperMsgGenerator_tickSize_1_0_Test.class, EWrapperMsgGenerator_tickOptionComputation_2_2_Test.class, EWrapperMsgGenerator_tickGeneric_3_0_Test.class, EWrapperMsgGenerator_tickString_4_0_Test.class, EWrapperMsgGenerator_updateAccountValue_9_0_Test.class, EWrapperMsgGenerator_updatePortfolio_10_0_Test.class, EWrapperMsgGenerator_updateAccountTime_11_0_Test.class, EWrapperMsgGenerator_accountDownloadEnd_12_4_Test.class, EWrapperMsgGenerator_nextValidId_13_2_Test.class, EWrapperMsgGenerator_contractDetailsEnd_18_0_Test.class, EWrapperMsgGenerator_updateMktDepth_21_3_Test.class, EWrapperMsgGenerator_updateMktDepthL2_22_1_Test.class, EWrapperMsgGenerator_updateNewsBulletin_23_0_Test.class, EWrapperMsgGenerator_managedAccounts_24_4_Test.class, EWrapperMsgGenerator_receiveFA_25_0_Test.class, EWrapperMsgGenerator_historicalData_26_1_Test.class, EWrapperMsgGenerator_scannerParameters_28_0_Test.class, EWrapperMsgGenerator_scannerDataEnd_30_1_Test.class, EWrapperMsgGenerator_currentTime_31_1_Test.class, EWrapperMsgGenerator_fundamentalData_32_0_Test.class })
public class EWrapperMsgGenerator_Suite {
}
