package com.ib.client;

import org.junit.runner.RunWith;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectClasses;

@RunWith(value = JUnitPlatform.class)
@SelectClasses(value = { EWrapperMsgGenerator_tickPrice_0_0_Test.class, EWrapperMsgGenerator_tickSize_1_0_Test.class, EWrapperMsgGenerator_tickOptionComputation_2_1_Test.class, EWrapperMsgGenerator_tickGeneric_3_0_Test.class, EWrapperMsgGenerator_tickString_4_0_Test.class, EWrapperMsgGenerator_tickEFP_5_0_Test.class, EWrapperMsgGenerator_orderStatus_6_0_Test.class, EWrapperMsgGenerator_openOrderEnd_8_0_Test.class, EWrapperMsgGenerator_updateAccountValue_9_0_Test.class, EWrapperMsgGenerator_updatePortfolio_10_0_Test.class, EWrapperMsgGenerator_updateAccountTime_11_0_Test.class, EWrapperMsgGenerator_accountDownloadEnd_12_0_Test.class, EWrapperMsgGenerator_nextValidId_13_0_Test.class, EWrapperMsgGenerator_contractDetails_14_3_Test.class, EWrapperMsgGenerator_contractMsg_16_1_Test.class, EWrapperMsgGenerator_bondContractDetails_17_2_Test.class, EWrapperMsgGenerator_contractDetailsEnd_18_0_Test.class, EWrapperMsgGenerator_execDetailsEnd_20_0_Test.class, EWrapperMsgGenerator_updateMktDepth_21_0_Test.class, EWrapperMsgGenerator_updateMktDepthL2_22_0_Test.class, EWrapperMsgGenerator_updateNewsBulletin_23_0_Test.class, EWrapperMsgGenerator_managedAccounts_24_0_Test.class, EWrapperMsgGenerator_receiveFA_25_2_Test.class, EWrapperMsgGenerator_historicalData_26_0_Test.class, EWrapperMsgGenerator_realtimeBar_27_0_Test.class, EWrapperMsgGenerator_scannerParameters_28_0_Test.class, EWrapperMsgGenerator_scannerData_29_4_Test.class, EWrapperMsgGenerator_scannerDataEnd_30_0_Test.class, EWrapperMsgGenerator_currentTime_31_0_Test.class, EWrapperMsgGenerator_fundamentalData_32_0_Test.class, EWrapperMsgGenerator_deltaNeutralValidation_33_2_Test.class, EWrapperMsgGenerator_tickSnapshotEnd_34_0_Test.class })
public class EWrapperMsgGenerator_Suite {
}
