package com.ib.client;

import org.junit.runner.RunWith;
import org.junit.platform.runner.JUnitPlatform;
import org.junit.platform.suite.api.SelectClasses;

@RunWith(value = JUnitPlatform.class)
@SelectClasses(value = { EWrapperMsgGenerator_tickPrice_0_0_Test.class, EWrapperMsgGenerator_tickSize_1_0_Test.class, EWrapperMsgGenerator_tickOptionComputation_2_0_Test.class, EWrapperMsgGenerator_tickGeneric_3_0_Test.class, EWrapperMsgGenerator_tickString_4_0_Test.class, EWrapperMsgGenerator_tickEFP_5_0_Test.class, EWrapperMsgGenerator_orderStatus_6_0_Test.class, EWrapperMsgGenerator_openOrder_7_0_Test.class, EWrapperMsgGenerator_openOrderEnd_8_0_Test.class, EWrapperMsgGenerator_updateAccountValue_9_0_Test.class, EWrapperMsgGenerator_updatePortfolio_10_0_Test.class, EWrapperMsgGenerator_updateAccountTime_11_1_Test.class, EWrapperMsgGenerator_accountDownloadEnd_12_2_Test.class, EWrapperMsgGenerator_nextValidId_13_0_Test.class, EWrapperMsgGenerator_contractDetailsEnd_18_2_Test.class, EWrapperMsgGenerator_execDetailsEnd_20_0_Test.class, EWrapperMsgGenerator_updateMktDepth_21_1_Test.class, EWrapperMsgGenerator_updateMktDepthL2_22_0_Test.class, EWrapperMsgGenerator_updateNewsBulletin_23_0_Test.class, EWrapperMsgGenerator_managedAccounts_24_1_Test.class, EWrapperMsgGenerator_receiveFA_25_1_Test.class, EWrapperMsgGenerator_historicalData_26_0_Test.class, EWrapperMsgGenerator_realtimeBar_27_0_Test.class, EWrapperMsgGenerator_scannerParameters_28_0_Test.class, EWrapperMsgGenerator_tickEFP_5_1_Test.class, EWrapperMsgGenerator_openOrder_7_1_Test.class, EWrapperMsgGenerator_openOrderEnd_8_2_Test.class })
public class EWrapperMsgGenerator_Suite {
}
